<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 18/1/25
 * Time: 下午10:54
 */

namespace behavior\Strategy;


class ConcreteStrategyA extends Strategy
{
    public function algrithmInterface()
    {
        // TODO: Change the autogenerated stub
        echo "《ConcreteStrategyA》";
    }
}