<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 18/1/22
 * Time: 上午1:05
 */

namespace create\AbstractFactory;


class FactoryProductX1 extends AbstractFactory
{
    public function createProduct0X()
    {
        parent::createProduct0X(); // TODO: Change the autogenerated stub
        return new Product01();
    }

    public function createProduct1X()
    {
        parent::createProduct1X(); // TODO: Change the autogenerated stub
        return new Product11();
    }
}