<?php
/**
 * Created by PhpStorm.
 * User: zhang
 * Date: 18/1/23
 * Time: 上午10:56
 */

namespace structure\AdapterInterface;

/**
 * @explain 实现类
 * Class Achieve
 * @package structure\AdapterInterface
 */
class Achieve extends Adapter
{
    function method01()
    {
        parent::method01(); // TODO: Change the autogenerated stub
        echo '《method01》';
    }

    function method02()
    {
        parent::method02(); // TODO: Change the autogenerated stub
        echo '《method02》';
    }
}